version: "3.5"
services:
  firestore_emulator:
    build:
      context: ./docker/emulator
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./docker/emulator/mount
        target: /home/node/mount
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8200
    ports:
      - "4000:4000"
      - "8200:8200"
    networks:
      - default
  uspy-backend:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8200
      - USPY_MOCK_FIRESTORE_DATA=true
      - USPY_PROJECT_ID=dummy-project-id
      - USPY_DOMAIN=0.0.0.0
      - USPY_ENFORCE_LOCAL=true
      - USPY_MODE=local
    networks:
      - default
      - scraper_network
    depends_on:
      - firestore_emulator
networks:
  scraper_network:
    external:
      name: scraper_network
  default: